# SPDX-License-Identifier: Apache-2.0
DEVICE_PATH := device/samsung/gta3xlwifi

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53
TARGET_USES_64_BIT_BINDER := true
TARGET_BOARD_PLATFORM := universal7904
TARGET_BOOTLOADER_BOARD_NAME := universal7904
TARGET_SOC := exynos7904
BOARD_VENDOR := samsung
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# The exact source-built kernel and DTBO previously booted on this tablet.
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOT_HEADER_VERSION := 1
BOARD_KERNEL_CMDLINE := androidboot.hardware=exynos7904 androidboot.selinux=enforcing
BOARD_MKBOOTIMG_ARGS := --header_version 1 --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --board SRPSA25A005RU
BOARD_RECOVERY_MKBOOTIMG_ARGS := $(BOARD_MKBOOTIMG_ARGS)
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
# CWA1 loads initrd at 0x89000000 and DTB at 0x8a000000 (observed boot log).
# A larger ramdisk overlaps the DTB, even when the image fits RECOVERY.
BOARD_RECOVERYIMAGE_MAX_RAMDISK_SIZE := 16777216
BOARD_RAMDISK_USE_XZ := true

# Values read from the actual SM-T510 PIT; no repartitioning.
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 47185920
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3196059648
BOARD_VENDORIMAGE_PARTITION_SIZE := 343932928
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 327155712
BOARD_CACHEIMAGE_PARTITION_SIZE := 159383552
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_AVB_ENABLE := false
TARGET_OTA_ASSERT_DEVICE := gta3xlwifi
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

TW_THEME := portrait_hdpi
TARGET_SCREEN_WIDTH := 1200
TARGET_SCREEN_HEIGHT := 1920
TARGET_SCREEN_DENSITY := 240
TW_DEVICE_VERSION := sm-t510-native-test
TW_MTP_DEVICE := SM-T510
TW_HAS_DOWNLOAD_MODE := true
TW_NO_REBOOT_BOOTLOADER := true
TW_BRIGHTNESS_PATH := /sys/class/backlight/panel/brightness
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 128
# Exynos DECON starts in INIT and requires FBIOBLANK/UNBLANK before drawing.
# Skipping it leaves Samsung's splash visible while the TWRP UI runs in memory.
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
# FBE links recovery against this library. Declare it at BoardConfig time so
# recovery packaging sees it before Android.mk adds its implicit crypto flag.
TW_INCLUDE_LIBRESETPROP := true
TARGET_RECOVERY_DEVICE_MODULES += libresetprop
RECOVERY_LIBRARY_SOURCE_FILES += $(TARGET_OUT_SHARED_LIBRARIES)/libresetprop.so
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
TW_EXCLUDE_LPDUMP := true
